from os import getenv

from dotenv import load_dotenv

load_dotenv()

BOT_NAME = getenv('BOT_NAME')

LOG_PREFIX_INFO = getenv('LOG_PREFIX_INFO')
LOG_PREFIX_DONE = getenv('LOG_PREFIX_DONE')
LOG_PREFIX_ERROR = getenv('LOG_PREFIX_ERROR')
LOG_COLUMN_WIDTH = int(getenv('LOG_COLUMN_WIDTH'))
LOG_DATA_AS = getenv('LOG_DATA_AS')
LOG_TWITCH_AS = getenv('LOG_TWITCH_AS')
LOG_DISCORD_AS = getenv('LOG_DISCORD_AS')
LOG_PETAL_AS = getenv('LOG_PETAL_AS')
LOG_GENERAL_AS = getenv('LOG_GENERAL_AS')
LOG_COLUMN_WIDTH = int(getenv('LOG_COLUMN_WIDTH'))
LOGIN_ATTEMPT_MESSAGE = getenv('LOGIN_ATTEMPT_MESSAGE')
LOGIN_SUCCESS_MESSAGE = getenv('LOGIN_SUCCESS_MESSAGE')
LOGIN_AUTH_ERROR_MESSAGE = getenv('LOGIN_AUTH_ERROR_MESSAGE')
LOGIN_ERROR_MESSAGE = getenv('LOGIN_ERROR_MESSAGE')

DATA_PATH = getenv('DATA_PATH')

TWITCH_TOKEN = getenv('TWITCH_TOKEN')
BROADCASTER_CHANNEL = getenv('BROADCASTER_CHANNEL')

DISCORD_GUILD_NAME = getenv('DISCORD_GUILD_NAME')
DISCORD_LIVE_GUILD_NAME = getenv('DISCORD_LIVE_GUILD_NAME')

DISCORD_TOKEN = getenv('DISCORD_TOKEN')
DISCORD_BROADCASTER_ID = int(getenv('DISCORD_BROADCASTER_ID'))
DISCORD_STAFF_CHANNEL_ID = int(getenv('DISCORD_STAFF_CHANNEL_ID'))
DISCORD_SUBSCRIBER_ROLE_ID = int(getenv('DISCORD_SUBSCRIBER_ROLE_ID'))
DISCORD_ALERTS_CHANNEL_ID = int(getenv('DISCORD_ALERTS_CHANNEL_ID'))
DISCORD_REACTION_ROLES_CHANNEL_ID = int(getenv('DISCORD_REACTION_ROLES_CHANNEL_ID'))
DISCORD_REACTION_ROLES_ALERTS_EMOJI = getenv('DISCORD_REACTION_ROLES_ALERTS_EMOJI')
DISCORD_REACTION_ROLES_RESCUE_EMOJI = getenv('DISCORD_REACTION_ROLES_RESCUE_EMOJI')
DISCORD_ALERTS_ROLE_ID = int(getenv('DISCORD_ALERTS_ROLE_ID'))
DISCORD_TIMER_ALERTS_ROLE_ID = int(getenv('DISCORD_TIMER_ALERTS_ROLE_ID'))
DISCORD_CLOSED_VOICE_CHANNEL_ID = int(getenv('DISCORD_CLOSED_VOICE_CHANNEL_ID'))
DISCORD_LIVE_VOICE_CHANNEL_ID = int(getenv('DISCORD_LIVE_VOICE_CHANNEL_ID'))
DISCORD_BRIDGE_CHANNEL_ID = int(getenv('DISCORD_BRIDGE_CHANNEL_ID'))
DISCORD_CHANNEL_IDS = set(map(int, getenv('DISCORD_CHANNEL_IDS').split(',')))

TWITTER_KEY = getenv('TWITTER_KEY')
TWITTER_SECRET = getenv('TWITTER_SECRET')
TWITTER_ACCESS_TOKEN = getenv('TWITTER_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET = getenv('TWITTER_ACCESS_TOKEN_SECRET')

TWITTER_DISPLAY_NAME = getenv('TWITTER_DISPLAY_NAME')
TWITTER_LIVE_DISPLAY_NAME = getenv('TWITTER_LIVE_DISPLAY_NAME')

LIVE_INDICATOR_TIMEOUT = int(getenv('LIVE_INDICATOR_TIMEOUT'))

PETAL_EMOJI = '🌺'
PETAL_SERVER = getenv('PETAL_SERVER')
PETAL_NAME = getenv('PETAL_NAME')
PETAL_TOKEN = getenv('PETAL_TOKEN')

DISCORD_ALERT_FORMAT = '<@&{}>\n\n{} ({})\n\nhttps://twitch.tv/{}'
TWITTER_ALERT_FORMAT = '{} ({})\n\nhttps://twitch.tv/{}'

DEFAULT_PREFIX = getenv('DEFAULT_PREFIX')
DEFAULT_CURRENCY_EMOJI = getenv('DEFAULT_CURRENCY_EMOJI')

DISCORD_PREFIX_KEY = 'prefix:discord'
TWITCH_PREFIX_KEY = 'prefix:twitch'
PETAL_PREFIX_KEY = 'prefix:petal'

EMOTE_VALUE_EXPONENT = 0.5
PARTIAL_BAL_PER_BAL = 10

RARITY_COMMON = 'Common'
RARITY_UNCOMMON = 'Uncommon'
RARITY_RARE = 'Rare'
RARITY_MYTHIC = 'Mythic'
RARITY_LEGENDARY = 'Legendary'
RARITY_STATS = {
  RARITY_COMMON: 1,
  RARITY_UNCOMMON: 2,
  RARITY_RARE: 3,
  RARITY_MYTHIC: 4,
  RARITY_LEGENDARY: 5
}

INVENTORY_TEMPLATE = 'Inventory:\n```md\n{}\n```'

SUBATHON_TIMER_FILE = getenv('SUBATHON_TIMER_FILE')
# in seconds
SUBATHON_TIMER_ALERT_TIMEOUT = int(getenv('SUBATHON_TIMER_ALERT_TIMEOUT'))
# in minutes
SUBATHON_TIMER_ALERT_THRESHOLD = int(getenv('SUBATHON_TIMER_ALERT_THRESHOLD'))
SUBATHON_TIMER_ALERT_FORMAT = '<@&{}>\n\nThe subathon could end in less than **' + str(SUBATHON_TIMER_ALERT_THRESHOLD) + ' minutes!** Donate, cheer, or gift subs to protect the subathon!\n\nhttps://twitch.tv/{}'
